# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(CMAKE_COMMAND) -E cmake_progress_start /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc/CMakeFiles /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc/external/IOC_Config//CMakeFiles/progress.marks
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/IOC_Config/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/IOC_Config/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/IOC_Config/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/IOC_Config/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
external/IOC_Config/CMakeFiles/ioc_config_static.dir/rule:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/IOC_Config/CMakeFiles/ioc_config_static.dir/rule
.PHONY : external/IOC_Config/CMakeFiles/ioc_config_static.dir/rule

# Convenience name for target.
ioc_config_static: external/IOC_Config/CMakeFiles/ioc_config_static.dir/rule
.PHONY : ioc_config_static

# fast build rule for target.
ioc_config_static/fast:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_Config/CMakeFiles/ioc_config_static.dir/build.make external/IOC_Config/CMakeFiles/ioc_config_static.dir/build
.PHONY : ioc_config_static/fast

# Convenience name for target.
external/IOC_Config/CMakeFiles/ioc_config_shared.dir/rule:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external/IOC_Config/CMakeFiles/ioc_config_shared.dir/rule
.PHONY : external/IOC_Config/CMakeFiles/ioc_config_shared.dir/rule

# Convenience name for target.
ioc_config_shared: external/IOC_Config/CMakeFiles/ioc_config_shared.dir/rule
.PHONY : ioc_config_shared

# fast build rule for target.
ioc_config_shared/fast:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_Config/CMakeFiles/ioc_config_shared.dir/build.make external/IOC_Config/CMakeFiles/ioc_config_shared.dir/build
.PHONY : ioc_config_shared/fast

src/oop_parser.o: src/oop_parser.cpp.o
.PHONY : src/oop_parser.o

# target to build an object file
src/oop_parser.cpp.o:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_Config/CMakeFiles/ioc_config_static.dir/build.make external/IOC_Config/CMakeFiles/ioc_config_static.dir/src/oop_parser.cpp.o
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_Config/CMakeFiles/ioc_config_shared.dir/build.make external/IOC_Config/CMakeFiles/ioc_config_shared.dir/src/oop_parser.cpp.o
.PHONY : src/oop_parser.cpp.o

src/oop_parser.i: src/oop_parser.cpp.i
.PHONY : src/oop_parser.i

# target to preprocess a source file
src/oop_parser.cpp.i:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_Config/CMakeFiles/ioc_config_static.dir/build.make external/IOC_Config/CMakeFiles/ioc_config_static.dir/src/oop_parser.cpp.i
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_Config/CMakeFiles/ioc_config_shared.dir/build.make external/IOC_Config/CMakeFiles/ioc_config_shared.dir/src/oop_parser.cpp.i
.PHONY : src/oop_parser.cpp.i

src/oop_parser.s: src/oop_parser.cpp.s
.PHONY : src/oop_parser.s

# target to generate assembly for a file
src/oop_parser.cpp.s:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_Config/CMakeFiles/ioc_config_static.dir/build.make external/IOC_Config/CMakeFiles/ioc_config_static.dir/src/oop_parser.cpp.s
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(MAKE) $(MAKESILENT) -f external/IOC_Config/CMakeFiles/ioc_config_shared.dir/build.make external/IOC_Config/CMakeFiles/ioc_config_shared.dir/src/oop_parser.cpp.s
.PHONY : src/oop_parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ioc_config_shared"
	@echo "... ioc_config_static"
	@echo "... src/oop_parser.o"
	@echo "... src/oop_parser.i"
	@echo "... src/oop_parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/michelebigi/Documents/Develop/ASTDYN/IOccultCalc && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

